# Generated by Django 3.1.4 on 2020-12-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_adde',
            new_name='date_added',
        ),
    ]
